### ISSUE TITLE
Dont install this, its a cookie logger

### ISSUE THREAD

**Issue by ghost** [vesperpew/Roblox-Account-Recovery#1]

**Comment by TrickyTay** [comment]
Well it seems that I was wrong. Some cookie loggers use .bat files to install requirements but I would still check whats in the .bat file before installing.

**Comment by vesperpew** [comment]
> Well it seems that I was wrong. Some cookie loggers use .bat files to install requirements but I would still check whats in the .bat file before installing.

I don't understand the point of making an issue of this kind on a open source project that took me 20 minutes to code. Please get a little more knowledge about the language Python before posting issues..

**Comment by nightowl-devs** [comment]
bro is actually retarted can't u fucing read the web hook is not even pasted in bro get some help
